"use client";
import React, { useRef, useState } from "react";
import { useLanguage } from "./LanguageContext";
import { LanguageSwitcher } from "./LanguageSwitcher";
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import jsPDF from "jspdf";
import { toJpeg } from "html-to-image";

export function ReportView({ report, parsedData, onNewSurvey }: { report: any; parsedData: any; onNewSurvey?: () => void }) {
  const { t } = useLanguage();
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);

  const exportPDF = async () => {
    if (!reportRef.current) return;
    try {
      setIsExporting(true);
      
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const marginX = 18;
      const marginY = 20;
      const renderWidth = pdfWidth - marginX * 2;
      
      const img = new Image();
      img.src = report.annotatedOriginalImage;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      let targetWidth = renderWidth;
      let targetHeight = (img.height * targetWidth) / img.width;
      const maxH = pageHeight - marginY * 2;
      if (targetHeight > maxH) {
        const sf = maxH / targetHeight;
        targetHeight = maxH;
        targetWidth = targetWidth * sf;
      }
      const offsetX = marginX + (renderWidth - targetWidth) / 2;
      
      pdf.addImage(report.annotatedOriginalImage, "PNG", offsetX, marginY, targetWidth, targetHeight);
      
      pdf.save(`AquaScan_Report_${report.customerName}.pdf`);
    } catch (error) {
      console.error("PDF Export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  const surveyDate = new Date().toLocaleDateString();

  const hasDrillingPoint = parsedData.recommendedDrillingDepth && parsedData.recommendedDrillingDepth !== "No reliable drilling point detected.";
  const bestDrillingPointVal = hasDrillingPoint ? (parsedData.bestBorewellPoint?.id || "Water Zone 1") : "No reliable drilling point detected.";
  const recommendedRangeVal = parsedData.recommendedDrillingDepth || parsedData.bestBorewellPoint?.depth || "N/A";
  const startDepthVal = hasDrillingPoint ? (parsedData.startDepth || parsedData.bestBorewellPoint?.startDepth || "N/A") : "N/A";
  const endDepthVal = hasDrillingPoint ? (parsedData.endDepth || parsedData.bestBorewellPoint?.endDepth || "N/A") : "N/A";

  return (
    <div className="min-h-screen bg-slate-50 p-4 sm:p-8">
      <div className="max-w-5xl mx-auto mb-6 flex justify-between items-center">
        <h1 className="text-2xl font-bold text-slate-800">{t("title")}</h1>
        <div className="flex gap-4 items-center">
          <LanguageSwitcher />
          <Button onClick={exportPDF} disabled={isExporting} className="bg-blue-600 hover:bg-blue-700">
            {isExporting ? "Generating PDF..." : t("exportPDF") || "Download PDF"}
          </Button>
          {onNewSurvey && (
            <Button onClick={onNewSurvey} variant="outline">New Survey</Button>
          )}
        </div>
      </div>

      <div ref={reportRef} className="max-w-5xl mx-auto flex flex-col gap-8">
        
        {/* FINAL PROFESSIONAL REPORT IMAGE */}
        <div id="section-final-report" className="bg-white border rounded-xl shadow-sm p-2 sm:p-4" style={{ borderColor: '#e2e8f0' }}>
          <div className="relative w-full border rounded overflow-hidden" style={{ borderColor: '#e2e8f0' }}>
            <img src={report.annotatedOriginalImage} alt="Professional Geological Report" className="w-full h-auto object-contain block" crossOrigin="anonymous" />
          </div>
        </div>

        <div className="text-center text-sm py-4" style={{ color: '#94a3b8' }}>
          Generated by AquaScan AI • Professional Borewell Analysis
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pb-8 print:hidden">
          <Button onClick={exportPDF} disabled={isExporting} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-6 px-8 rounded-lg shadow-lg text-lg w-full sm:w-auto">
            {isExporting ? "Generating PDF..." : "Download PDF Report"}
          </Button>
          {onNewSurvey && (
            <Button onClick={onNewSurvey} variant="outline" className="border-2 border-slate-300 hover:bg-slate-100 text-slate-700 font-bold py-6 px-8 rounded-lg shadow text-lg w-full sm:w-auto">
              Create New Survey
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}
